### ISSUE TITLE
Enhancement Request: Allow SSLContext to be injected while creating a Session

### ISSUE THREAD

**Issue by tbdasap** [yahoo/smtp-client-nio#30]
[SmtpAsyncClient](https://github.com/yahoo/smtp-client-nio/blob/master/core/src/main/java/com/yahoo/smtpnio/async/client/SmtpAsyncClient.java#L293) creates and uses a `default` SSLcontext when creating a TLS/SSL session. In some usecases, a client certificate may need to be presented which is possibly only by passing in a suitably configured SSLcontext. 

## Description

This is an enhancement request.

## Expected Behavior

Add the ability to inject a suitably configured SSLContext.

## Actual Behavior

Currently this is not possible as a default SSLcontext is being used.

## Possible Fix

1. Add `Nullable SSLContext` to [SmtpSessionData (and builder)](https://github.com/yahoo/smtp-client-nio/blob/master/core/src/main/java/com/yahoo/smtpnio/async/client/SmtpAsyncSessionData.java#L63-L65)
2. Use if non-null to create a `secure` session.

## Steps to Reproduce

1. N/A

## Your Environment

* Version used: 1.0.7
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): JDK 15
* Server type and version: N/A
* Operating System and version: RHEL7, OSX
* Link to your project: N/A

**Comment by rockwotj** [comment]
Can this be closed now that #31 is merged?
